class AppStrings {
  static String currentLang = 'hi';

  static final Map<String, Map<String, String>> _localizedValues = {
    'hi': {
      'app_title': 'टीम गोपालसिंह - हरनावदा गजा',
      'tagline': 'गांव की आवाज़ • गांव का विकास • गांव के साथ',
      'nav_home': 'मुख्य पृष्ठ',
      'nav_complaint': 'शिकायत दर्ज',
      'nav_development': 'विकास कार्य',
      'nav_directory': 'अधिकारी',
      'nav_more': 'अन्य जानकारी',
      'quick_actions': 'त्वरित सेवाएं',
      'action_complaint': '📢 शिकायत दर्ज करें',
      'action_development': '🏗️ विकास कार्य',
      'action_news': '📰 गांव की खबरें',
      'action_schemes': '📋 सरकारी योजनाएं',
      'surya_mandir_hero_title': 'ऐतिहासिक सूर्य मंदिर, झालरापाटन',
      'surya_mandir_hero_subtitle': '10वीं शताब्दी का वास्तुकला रत्न एवं सांस्कृतिक धरोहर',
      'surya_mandir_btn': 'सूर्य मंदिर के बारे में जानें →',
      'constituency_title': 'झालरापाटन विधानसभा क्षेत्र (AC-198)',
      'district_label': 'जिला: झालावाड़, राजस्थान',
      'sampark_portal_btn': 'राजस्थान संपर्क पोर्टल 181 पर जाएं',
      'disclaimer_title': 'गैर-सरकारी घोषणापत्र (Non-Government Disclaimer)',
      'disclaimer_text': 'यह ऐप टीम गोपालसिंह द्वारा केवल जन-सेवा, विकास सूचना एवं सहायता हेतु संचालित है। यह किसी भी सरकारी संस्था, राजस्थान सरकार या चुनाव आयोग का आधिकारिक ऐप नहीं है।',
      'submit_complaint': 'शिकायत दर्ज करें',
      'complaint_category': 'शिकायत की श्रेणी',
      'complaint_desc': 'समस्या का विवरण',
      'photo_attach': 'फ़ोटो/दस्तावेज़ संलग्न करें',
      'get_location': 'GPS स्थान प्राप्त करें',
      'ref_number': 'संदर्भ संख्या (Reference ID)',
      'officer_directory': 'प्रशासनिक संपर्क सूची',
      'verified_source': 'सत्यापित स्रोत:',
      'call': 'कॉल करें',
      'email': 'ईमेल भेजें',
      'directions': 'दिशा-निर्देश',
      'election_center': 'चुनाव एवं मतदाता केंद्र',
      'harnawada_info': 'ग्राम पंचायत हरनावदा गजा',
      'schemes': 'जन कल्याणकारी योजनाएं',
      'profile': 'प्रोफ़ाइल एवं सेटिंग्स',
      'language_switch': 'भाषा बदलें (Language)',
    },
    'en': {
      'app_title': 'Team GopalSingh - Harnawada Gaja',
      'tagline': 'Voice of Village • Development • Together',
      'nav_home': 'Home',
      'nav_complaint': 'Grievance',
      'nav_development': 'Development',
      'nav_directory': 'Directory',
      'nav_more': 'More',
      'quick_actions': 'Quick Actions',
      'action_complaint': '📢 File Grievance',
      'action_development': '🏗️ Village Development',
      'action_news': '📰 Village News',
      'action_schemes': '📋 Govt Schemes',
      'surya_mandir_hero_title': 'Historic Surya Mandir, Jhalrapatan',
      'surya_mandir_hero_subtitle': '10th Century Architectural Gem & Heritage Site',
      'surya_mandir_btn': 'Learn About Surya Mandir →',
      'constituency_title': 'Jhalrapatan Assembly Constituency (AC-198)',
      'district_label': 'District: Jhalawar, Rajasthan',
      'sampark_portal_btn': 'Launch Rajasthan Sampark 181',
      'disclaimer_title': 'Non-Government Disclaimer',
      'disclaimer_text': 'This application is operated by Team GopalSingh purely for public welfare and information. It is NOT an official app of any government entity or election commission.',
      'submit_complaint': 'Submit Complaint',
      'complaint_category': 'Select Category',
      'complaint_desc': 'Description of Issue',
      'photo_attach': 'Attach Photo / Document',
      'get_location': 'Get GPS Location',
      'ref_number': 'Reference ID',
      'officer_directory': 'Official Contact Directory',
      'verified_source': 'Verified Source:',
      'call': 'Call',
      'email': 'Email',
      'directions': 'Directions',
      'election_center': 'Election & Voter Center',
      'harnawada_info': 'Gram Panchayat Harnawada Gaja',
      'schemes': 'Government Schemes',
      'profile': 'Profile & Settings',
      'language_switch': 'Switch Language',
    }
  };

  static String get(String key) {
    return _localizedValues[currentLang]?[key] ?? _localizedValues['hi']![key] ?? key;
  }
}
